import { SharedMemory } from "@repo/core/adapters/mock";
import { QuotationStatus, OrderDeliveryMode } from "@repo/core/models";

export const setup = () => {
    SharedMemory.quotations = [
        {
            id: 1,
            title: "Quotation 1",
            orderId: 101,
            clubId: 1,
            status: QuotationStatus.EN_ATTENTE,
            totalAmount: 250.00,
            shippingFees: 10,
            rest: 240,
            withoutTVA: false,
            totalDiscount: 0,
            clientComment: "",
            usedCredit: 0,
            version: 1,
            clientNumber: 1,
            createdAt: new Date("2024-06-01"),
            deliveryMode: OrderDeliveryMode.AU_CLUB,
            
        },
        {
            id: 2,
            title: "Quotation 2",
            orderId: 102,
            clubId: 2,
            status: QuotationStatus.VALIDE,
            totalAmount: 170.00,
            shippingFees: 10,
            rest: 160,
            withoutTVA: false,
            totalDiscount: 0,
            clientComment: "",
            usedCredit: 0,
            version: 1,
            clientNumber: 2,
            createdAt: new Date("2024-05-28"),
            deliveryMode: OrderDeliveryMode.CHRONOPOST,
            
        },
        {
            id: 3,
            title: "Quotation 3",
            orderId: 103,
            clubId: 3,
            status: QuotationStatus.ARCHIVE,
            totalAmount: 310.00,
            shippingFees: 10,
            rest: 300,
            withoutTVA: false,
            totalDiscount: 0,
            clientComment: "",
            usedCredit: 0,
            version: 1,
            clientNumber: 3,
            createdAt: new Date("2024-05-20"),
            deliveryMode: OrderDeliveryMode.COLISSIMO,
        },
        {
            id: 4,
            title: "Quotation 4",
            orderId: 104,
            clubId: 2,
            status: QuotationStatus.EN_ATTENTE,
            totalAmount: 120.00,
            shippingFees: 10,
            rest: 110,
            withoutTVA: false,
            totalDiscount: 0,
            clientComment: "",
            usedCredit: 0,
            version: 1,
            clientNumber: 4,
            createdAt: new Date("2024-06-05"),
            deliveryMode: OrderDeliveryMode.ICI_RELAIS,
            
        },
        {
            id: 5,
            title: "Quotation 5",
            orderId: 105,
            clubId: 1,
            status: QuotationStatus.VALIDE,
            totalAmount: 275.50,
            shippingFees: 10,
            rest: 265.5,
            withoutTVA: false,
            totalDiscount: 0,
            clientComment: "",
            usedCredit: 0,
            version: 1,
            clientNumber: 5,
            createdAt: new Date("2024-05-18"),
            deliveryMode: OrderDeliveryMode.CHRONOPOST_RELAIS,
            
        },
        {
            id: 6,
            title: "Quotation 6",
            orderId: 106,
            clubId: 4,
            status: QuotationStatus.EN_ATTENTE,
            totalAmount: 198.00,
            shippingFees: 10,
            rest: 188,
            withoutTVA: false,
            totalDiscount: 0,
            clientComment: "",
            usedCredit: 0,
            version: 1,
            clientNumber: 6,
            createdAt: new Date("2024-06-03"),
            deliveryMode: OrderDeliveryMode.SO_COLISSIMO,
            
        },
        {
            id: 7,
            title: "Quotation 7",
            orderId: 107,
            clubId: 2,
            status: QuotationStatus.ARCHIVE,
            totalAmount: 90.00,
            shippingFees: 10,
            rest: 80,
            withoutTVA: false,
            totalDiscount: 0,
            clientComment: "",
            usedCredit: 0,
            version: 1,
            clientNumber: 7,
            createdAt: new Date("2024-06-01"),
            deliveryMode: OrderDeliveryMode.MONDIAL_RELAY,
            
        },
        {
            id: 8,
            title: "Quotation 8",
            orderId: 108,
            clubId: 3,
            status: QuotationStatus.VALIDE,
            totalAmount: 55.00,
            shippingFees: 10,
            rest: 45,
            withoutTVA: false,
            totalDiscount: 0,
            clientComment: "",
            usedCredit: 0,
            version: 1,
            clientNumber: 8,
            createdAt: new Date("2024-05-30"),
            deliveryMode: OrderDeliveryMode.ICI_RELAIS,
            
        },
        {
            id: 9,
            title: "Quotation 9",
            orderId: 109,
            clubId: 1,
            status: QuotationStatus.EN_ATTENTE,
            totalAmount: 380.00,
            shippingFees: 10,
            rest: 370,
            withoutTVA: false,
            totalDiscount: 0,
            clientComment: "",
            usedCredit: 0,
            version: 1,
            clientNumber: 9,
            createdAt: new Date("2024-06-04"),
            deliveryMode: OrderDeliveryMode.COLISSIMO,
            
        },
        {
            id: 10,
            title: "Quotation 10",
            orderId: 110,
            clubId: 5,
            status: QuotationStatus.ARCHIVE,
            totalAmount: 145.00,
            shippingFees: 10,
            rest: 135,
            withoutTVA: false,
            totalDiscount: 0,
            clientComment: "",
            usedCredit: 0,
            version: 1,
            clientNumber: 10,
            createdAt: new Date("2024-05-25"),
            deliveryMode: OrderDeliveryMode.EXAPAQ,
            
        }
    ];
};

export const teardown = () => {
    SharedMemory.clear();
};
