import { SharedMemory } from "../../../src/adapters/mock";
import { ClientType, OrderDeliveryMode, OrderStatus, UserRoles } from "../../../src/models";

export const setup = () => {
    SharedMemory.users = [
        { id: "1", email: "admin@admin.com", user_role: UserRoles.SUPER_ADMIN, first_name: "Admin", last_name: "Admin", password: "admin", is_anonymous: false },
    ]
    
    SharedMemory.clients = [
        {
            userId: "1",
            email: "laurent.garnier@example.com",
            firstName: "Laurent",
            lastName: "Garnier",
            phone: "0147203891",
            mobilePhone: "0678293847",
            workPhone: "0156849201",
            clubMemberId: 4001,
            clubId: 1,
            clientNumber: 1,
            type: ClientType.CLIENT,
            lang: "fr",
            birthDate: new Date("1979-05-12"),
            newsLetter: true,
            siteOffer: false,
            partnerOffer: true,
            fidelityPoints: 150,
            credit: 25.00,
            club: {
                id: 1, name: "Club 1", president: "President 1", email: "president1@club1.com", accountantAccount: "1234567890", paymentMode: 1, paymentDelay: 1, phone: "0123456789", partner: true,
                referent: "",
                code: "",
                valid: false,
                siren: "",
                tvaNumber: "0"
            },
            clientAddress: [],
            order: [{
                id: 101, clientId: 1, amount: 50,
                createdAt: new Date(),
                status: OrderStatus.ATTENTE_ACCEPTATION_DEVIS,
                deliveryFees: 0,
                withoutVAT: false,
                quotation: false,
                deliveryMode: OrderDeliveryMode.COLISSIMO,
                usedCredit: 0,
                totalDiscount: 0,
                authorisation: "",
                paymentMode: "",
                authorisationDate: new Date()
            }],
            quotation: [],
            createdAt: new Date()
        },
        {
            userId: "2",
            email: "claire.morel@example.com",
            firstName: "Claire",
            lastName: "Morel",
            phone: "0182937461",
            mobilePhone: "0691827364",
            workPhone: "0134958261",
            clubMemberId: 4002,
            clubId: 2,
            clientNumber: 2,
            type: ClientType.CLUB,
            lang: "fr",
            birthDate: new Date("1988-08-20"),
            newsLetter: false,
            siteOffer: true,
            partnerOffer: false,
            fidelityPoints: 95,
            credit: 17.50,
            club: { id: 2, name: "Club 2", president: "President 2", email: "president2@club2.com", accountantAccount: "1234567890", paymentMode: 1, paymentDelay: 1
                , referent: "Referent 2", partner: true, phone: "0123456789", code: "1234567890", valid: true, siren: "1234567890", tvaNumber: "1234567890" },
            clientAddress: [{
                id: 2,
                numero_client: 2,
                designation: "",
                civilite: "",
                nom: "",
                prenom: "",
                adresse: "",
                adresse2: "",
                adresse3: "",
                code_postal: "69001",
                ville: "Lyon",
                pays: "",
                interphone: "",
                code_porte: "",
                instructions: "",
                default: false,
                created_at: new Date(),
                updated_at: new Date(),
                societe: ""
            }],
            order: [{
                id: 102, clientId: 2, amount: 75,
                createdAt: new Date(),
                status: OrderStatus.ATTENTE_ACCEPTATION_DEVIS,
                deliveryFees: 0,
                withoutVAT: false,
                quotation: false,
                deliveryMode: OrderDeliveryMode.COLISSIMO,
                usedCredit: 0,
                totalDiscount: 0,
                authorisation: "",
                paymentMode: "",
                authorisationDate: new Date()
            }],
            quotation: [],
            createdAt: new Date()
        },
        {
            userId: "3",
            email: "hugo.lefevre@example.com",
            firstName: "Hugo",
            lastName: "Lefèvre",
            phone: "0173829402",
            mobilePhone: "0657382940",
            workPhone: "0147392018",
            clubMemberId: 4003,
            clubId: 3,
            clientNumber: 3,
            type: ClientType.CLUB_PARTENAIRE,
            lang: "fr",
            birthDate: new Date("1992-01-14"),
            newsLetter: true,
            siteOffer: true,
            partnerOffer: true,
            fidelityPoints: 280,
            credit: 62.80,
            club: { id: 3, name: "Club 3", president: "President 3", email: "president3@club3.com", accountantAccount: "1234567890", paymentMode: 1, paymentDelay: 1
                , referent: "Referent 3", partner: true, phone: "0123456789", code: "1234567890", valid: true, siren: "1234567890", tvaNumber: "1234567890" },
            clientAddress: [{
                id: 3,
                numero_client: 3,
                designation: "",
                civilite: "",
                nom: "",
                prenom: "",
                adresse: "",
                adresse2: "",
                adresse3: "",
                code_postal: "33000",
                ville: "Bordeaux",
                pays: "",
                interphone: "",
                code_porte: "",
                instructions: "",
                default: false,
                created_at: new Date(),
                updated_at: new Date(),
                societe: ""
            }],
            order: [{
                id: 103, clientId: 3, amount: 100,
                createdAt: new Date(),
                status: OrderStatus.ATTENTE_ACCEPTATION_DEVIS,
                deliveryFees: 0,
                withoutVAT: false,
                quotation: false,
                deliveryMode: OrderDeliveryMode.COLISSIMO,
                usedCredit: 0,
                totalDiscount: 0,
                authorisation: "",
                paymentMode: "",
                authorisationDate: new Date()
            }],
            quotation: [],
            createdAt: new Date()
        },
        {
            userId: "4",
            email: "elodie.bernard@example.com",
            firstName: "Élodie",
            lastName: "Bernard",
            phone: "0129384756",
            mobilePhone: "0638492019",
            workPhone: "0173849201",
            clubMemberId: 4004,
            clubId: 2,
            clientNumber: 4,
            type: ClientType.CLIENT,
            lang: "fr",
            birthDate: new Date("1990-10-30"),
            newsLetter: false,
            siteOffer: false,
            partnerOffer: true,
            fidelityPoints: 70,
            credit: 12.00,
            club: { id: 2, name: "Club 2", president: "President 2", email: "president2@club2.com", accountantAccount: "1234567890", paymentMode: 1, paymentDelay: 1
                , referent: "Referent 2", partner: true, phone: "0123456789", code: "1234567890", valid: true, siren: "1234567890", tvaNumber: "1234567890" },
            clientAddress: [{
                id: 4,
                numero_client: 4,
                designation: "",
                civilite: "",
                nom: "",
                prenom: "",
                adresse: "",
                adresse2: "",
                adresse3: "",
                code_postal: "31000",
                ville: "Toulouse",
                pays: "",
                interphone: "",
                code_porte: "",
                instructions: "",
                default: false,
                created_at: new Date(),
                updated_at: new Date(),
                societe: ""
            }],
            order: [{
                id: 104, clientId: 4, amount: 25,
                createdAt: new Date(),
                status: OrderStatus.ATTENTE_ACCEPTATION_DEVIS,
                deliveryFees: 0,
                withoutVAT: false,
                quotation: false,
                deliveryMode: OrderDeliveryMode.COLISSIMO,
                usedCredit: 0,
                totalDiscount: 0,
                authorisation: "",
                paymentMode: "",
                authorisationDate: new Date()
            }],
            quotation: [],
            createdAt: new Date()
        },
        {
            userId: "5",
            email: "benoit.renaud@example.com",
            firstName: "Benoît",
            lastName: "Renaud",
            phone: "0157492038",
            mobilePhone: "0673920183",
            workPhone: "0148293847",
            clubMemberId: 4005,
            clubId: 1,
            clientNumber: 5,
            type: ClientType.CLUB_PARTENAIRE,
            lang: "fr",
            birthDate: new Date("1981-03-22"),
            newsLetter: true,
            siteOffer: true,
            partnerOffer: false,
            fidelityPoints: 215,
            credit: 33.00,
            club: { id: 1, name: "Club 1", president: "President 1", email: "president1@club1.com", accountantAccount: "1234567890", paymentMode: 1, paymentDelay: 1
                , referent: "Referent 1", partner: true, phone: "0123456789", code: "1234567890", valid: true, siren: "1234567890", tvaNumber: "1234567890" },
            clientAddress: [{
                id: 5,
                numero_client: 5,
                designation: "",
                civilite: "",
                nom: "",
                prenom: "",
                adresse: "",
                adresse2: "",
                adresse3: "",
                code_postal: "44000",
                ville: "Nantes",
                pays: "",
                interphone: "",
                code_porte: "",
                instructions: "",
                default: false,
                created_at: new Date(),
                updated_at: new Date(),
                societe: ""
            }],
            order: [{
                id: 105, clientId: 5, amount: 60,
                createdAt: new Date(),
                status: OrderStatus.ATTENTE_ACCEPTATION_DEVIS,
                deliveryFees: 0,
                withoutVAT: false,
                quotation: false,
                deliveryMode: OrderDeliveryMode.COLISSIMO,
                usedCredit: 0,
                totalDiscount: 0,
                authorisation: "",
                paymentMode: "",
                authorisationDate: new Date()
            }],
            quotation: [],
            createdAt: new Date()
        },
        {
            userId: "6",
            email: "sandrine.perrot@example.com",
            firstName: "Sandrine",
            lastName: "Perrot",
            phone: "0146738290",
            mobilePhone: "0683749201",
            workPhone: "0148392018",
            clubMemberId: 4006,
            clubId: 4,
            clientNumber: 6,
            type: ClientType.CLIENT,
            lang: "fr",
            birthDate: new Date("1985-07-17"),
            newsLetter: false,
            siteOffer: true,
            partnerOffer: true,
            fidelityPoints: 122,
            credit: 19.90,
            club: { id: 4, name: "Club 4", president: "President 4", email: "president4@club4.com", accountantAccount: "1234567890", paymentMode: 1, paymentDelay: 1
                , referent: "Referent 4", partner: true, phone: "0123456789", code: "1234567890", valid: true, siren: "1234567890", tvaNumber: "1234567890" },
            clientAddress: [{
                id: 6,
                numero_client: 6,
                designation: "",
                civilite: "",
                nom: "",
                prenom: "",
                adresse: "",
                adresse2: "",
                adresse3: "",
                code_postal: "06000",
                ville: "Nice",
                pays: "",
                interphone: "",
                code_porte: "",
                instructions: "",
                default: false,
                created_at: new Date(),
                updated_at: new Date(),
                societe: ""
            }],
            order: [{
                id: 106, clientId: 6, amount: 40,
                createdAt: new Date(),
                status: OrderStatus.ATTENTE_ACCEPTATION_DEVIS,
                deliveryFees: 0,
                withoutVAT: false,
                quotation: false,
                deliveryMode: OrderDeliveryMode.COLISSIMO,
                usedCredit: 0,
                totalDiscount: 0,
                authorisation: "",
                paymentMode: "",
                authorisationDate: new Date()
            }],
            quotation: [],
            createdAt: new Date()
        },
        {
            userId: "7",
            email: "mathieu.caron@example.com",
            firstName: "Mathieu",
            lastName: "Caron",
            phone: "0147382947",
            mobilePhone: "0673849201",
            workPhone: "0138492018",
            clubMemberId: 4007,
            clubId: 2,
            clientNumber: 7,
            type: ClientType.CLUB,
            lang: "fr",
            birthDate: new Date("1995-12-01"),
            newsLetter: true,
            siteOffer: false,
            partnerOffer: false,
            fidelityPoints: 64,
            credit: 10.00,
            club: { id: 2, name: "Club 2", president: "President 2", email: "president2@club2.com", accountantAccount: "1234567890", paymentMode: 1, paymentDelay: 1
                , referent: "Referent 2", partner: true, phone: "0123456789", code: "1234567890", valid: true, siren: "1234567890", tvaNumber: "1234567890" },
            clientAddress: [{
                id: 7,
                numero_client: 7,
                designation: "",
                civilite: "",
                nom: "",
                prenom: "",
                adresse: "",
                adresse2: "",
                adresse3: "",
                code_postal: "13000",
                ville: "Marseille",
                pays: "",
                interphone: "",
                code_porte: "",
                instructions: "",
                default: false,
                created_at: new Date(),
                updated_at: new Date(),
                societe: ""
            }],
            order: [{
                id: 107, clientId: 7, amount: 20,
                createdAt: new Date(),
                status: OrderStatus.ATTENTE_ACCEPTATION_DEVIS,
                deliveryFees: 0,
                withoutVAT: false,
                quotation: false,
                deliveryMode: OrderDeliveryMode.COLISSIMO,
                usedCredit: 0,
                totalDiscount: 0,
                authorisation: "",
                paymentMode: "",
                authorisationDate: new Date()
            }],
            quotation: [],
            createdAt: new Date()
        },
        {
            userId: "8",
            email: "chloe.marchand@example.com",
            firstName: "Chloé",
            lastName: "Marchand",
            phone: "0157382947",
            mobilePhone: "0693849201",
            workPhone: "0158392018",
            clubMemberId: 4008,
            clubId: 3,
            clientNumber: 8,
            type: ClientType.CLIENT,
            lang: "fr",
            birthDate: new Date("1998-04-08"),
            newsLetter: false,
            siteOffer: false,
            partnerOffer: false,
            fidelityPoints: 45,
            credit: 5.60,
            club: { id: 3, name: "Club 3", president: "President 3", email: "president3@club3.com", accountantAccount: "1234567890", paymentMode: 1, paymentDelay: 1
                , referent: "Referent 3", partner: true, phone: "0123456789", code: "1234567890", valid: true, siren: "1234567890", tvaNumber: "1234567890" },
            clientAddress: [{
                id: 8,
                numero_client: 8,
                designation: "",
                civilite: "",
                nom: "",
                prenom: "",
                adresse: "",
                adresse2: "",
                adresse3: "",
                code_postal: "14000",
                ville: "Caen",
                pays: "",
                interphone: "",
                code_porte: "",
                instructions: "",
                default: false,
                created_at: new Date(),
                updated_at: new Date(),
                societe: ""
            }],
            order: [{
                id: 108, clientId: 8, amount: 10,
                createdAt: new Date(),
                status: OrderStatus.ATTENTE_ACCEPTATION_DEVIS,
                deliveryFees: 0,
                withoutVAT: false,
                quotation: false,
                deliveryMode: OrderDeliveryMode.COLISSIMO,
                usedCredit: 0,
                totalDiscount: 0,
                authorisation: "",
                paymentMode: "",
                authorisationDate: new Date()
            }],
            quotation: [],
            createdAt: new Date()
        },
        {
            userId: "9",
            email: "eric.fontaine@example.com",
            firstName: "Éric",
            lastName: "Fontaine",
            phone: "0167382947",
            mobilePhone: "0643849201",
            workPhone: "0128392018",
            clubMemberId: 4009,
            clubId: 1,
            clientNumber: 9,
            type: ClientType.CLUB_PARTENAIRE,
            lang: "fr",
            birthDate: new Date("1983-09-19"),
            newsLetter: true,
            siteOffer: true,
            partnerOffer: true,
            fidelityPoints: 310,
            credit: 75.50,
            club: { id: 1, name: "Club 1", president: "President 1", email: "president1@club1.com", accountantAccount: "1234567890", paymentMode: 1, paymentDelay: 1
                , referent: "Referent 1", partner: true, phone: "0123456789", code: "1234567890", valid: true, siren: "1234567890", tvaNumber: "1234567890" },
            clientAddress: [{
                id: 9,
                numero_client: 9,
                designation: "",
                civilite: "",
                nom: "",
                prenom: "",
                adresse: "",
                adresse2: "",
                adresse3: "",
                code_postal: "35000",
                ville: "Rennes",
                pays: "",
                interphone: "",
                code_porte: "",
                instructions: "",
                default: false,
                created_at: new Date(),
                updated_at: new Date(),
                societe: ""
            }],
            order: [{
                id: 109, clientId: 9, amount: 90,
                createdAt: new Date(),
                status: OrderStatus.ATTENTE_ACCEPTATION_DEVIS,
                deliveryFees: 0,
                withoutVAT: false,
                quotation: false,
                deliveryMode: OrderDeliveryMode.COLISSIMO,
                usedCredit: 0,
                totalDiscount: 0,
                authorisation: "",
                paymentMode: "",
                authorisationDate: new Date()
            }],
            quotation: [],
            createdAt: new Date()
        },
        {
            userId: "10",
            email: "nathalie.colin@example.com",
            firstName: "Nathalie",
            lastName: "Colin",
            phone: "0148372947",
            mobilePhone: "0683849201",
            workPhone: "0118392018",
            clubMemberId: 4010,
            clubId: 5,
            clientNumber: 10,
            type: ClientType.CLIENT,
            lang: "fr",
            birthDate: new Date("1975-11-11"),
            newsLetter: false,
            siteOffer: true,
            partnerOffer: false,
            fidelityPoints: 88,
            credit: 20.00,
            club: { id: 5, name: "Club 5", president: "President 5", email: "president5@club5.com", accountantAccount: "1234567890", paymentMode: 1, paymentDelay: 1
                , referent: "Referent 5", partner: true, phone: "0123456789", code: "1234567890", valid: true, siren: "1234567890", tvaNumber: "1234567890" },
            clientAddress: [{
                id: 10,
                numero_client: 10,
                designation: "",
                civilite: "",
                nom: "",
                prenom: "",
                adresse: "",
                adresse2: "",
                adresse3: "",
                code_postal: "21000",
                ville: "Dijon",
                pays: "",
                interphone: "",
                code_porte: "",
                instructions: "",
                default: false,
                created_at: new Date(),
                updated_at: new Date(),
                societe: ""
            }],
            order: [{
                id: 110, clientId: 10, amount: 30,
                createdAt: new Date(),
                status: OrderStatus.ATTENTE_ACCEPTATION_DEVIS,
                deliveryFees: 0,
                withoutVAT: false,
                quotation: false,
                deliveryMode: OrderDeliveryMode.COLISSIMO,
                usedCredit: 0,
                totalDiscount: 0,
                authorisation: "",
                paymentMode: "",
                authorisationDate: new Date()
            }],
            quotation: [],
            createdAt: new Date()
        }
    ];
};

export const teardown = () => {
    SharedMemory.clear();
};
